version: "3"
services:
  api:
    container_name: api
    image: halyssonfreitas/api_ts
    ports:
      - "5000:3050"
    links:
      - link_db
    depends_on:
      - link_db
    
  link_db:
    container_name: link_db
    image: mongo
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
