version: "3"

networks:
  tetao:

services:
  api:
    container_name: api
    image: halysson/alpine_api_ts
    ports:
      - "3050:3050"
    links:
      - link_db
    depends_on:
      - link_db
    networks:
      - tetao

    
  link_db:
    container_name: link_db
    image: mongo
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
    networks:
      - tetao
